# Generated by Django 5.1.5 on 2025-01-22 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_profile_girwrs', upload_to='images/')),
                ('category', models.CharField(choices=[('seafood', 'Seafood'), ('vegetarian', 'Vegetarian'), ('cold', 'Cold Dishes'), ('warm', 'Warm Dishes'), ('desert', 'Desert'), ('others', 'Others')], default='others', max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
