# Generated by Django 5.1.5 on 2025-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('seafood', 'Seafood'), ('vegetarian', 'Vegetarian'), ('cold', 'Cold Dishes'), ('warm', 'Warm Dishes'), ('desert', 'Desert'), ('others', 'Others')], default='Others', max_length=60),
        ),
    ]
