# Generated by Django 5.1.5 on 2025-01-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_tag_alter_post_category_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, default='others', related_name='posts', to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('spicy', 'Spicy'), ('sweet', 'Sweet'), ('savory', 'Savory'), ('bitter', 'Bitter'), ('sour', 'Sour'), ('salty', 'Salty'), ('umami', 'Umami'), ('others', 'Others')], max_length=60, unique=True),
        ),
    ]
