# Generated by Django 5.1.5 on 2025-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_tags_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='posts.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('spicy', 'Spicy'), ('sweet', 'Sweet'), ('savory', 'Savory'), ('bitter', 'Bitter'), ('sour', 'Sour'), ('salty', 'Salty'), ('umami', 'Umami'), ('others', 'Others')], default='others', max_length=60),
        ),
    ]
