# Generated by Django 5.1.5 on 2025-01-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_tag_options_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('vintage', 'Vintage'), ('black_and_white', 'Black & White'), ('sepia', 'Sepia'), ('contrast', 'High Contrast'), ('bright', 'Bright'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
    ]
