# Generated by Django 5.1.5 on 2025-01-31 20:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_post_f3ugv9', max_length=255, verbose_name='images'),
        ),
    ]
