# Generated by Django 5.1.5 on 2025-02-07 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='v1737306345/default_post_f3ugv9.jpg', max_length=255, verbose_name='images'),
        ),
    ]
