# Generated by Django 5.1.5 on 2025-01-31 20:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_profile_girwrs', max_length=255, verbose_name='images'),
        ),
    ]
